"""Client for fetching App Store reviews."""

from __future__ import annotations

import asyncio
from pathlib import Path

from app_reviews.appstore.auth import ConnectAuth
from app_reviews.appstore.connect import AppStoreOfficialProvider
from app_reviews.appstore.rss import AppStoreScraperProvider
from app_reviews.core.http import HttpClient
from app_reviews.core.provider import ReviewProvider
from app_reviews.core.reviews import BaseReviews
from app_reviews.errors import AuthError
from app_reviews.models.config import AppStoreAuth, ConnectCredentials, RetryConfig


class AppStoreReviews(BaseReviews):
    """Client for fetching App Store reviews.

    With ``auth`` it reads the App Store Connect API; without, the public RSS feed.
    """

    def __init__(
        self,
        *,
        auth: AppStoreAuth | None = None,
        proxy: str | None = None,
        retry: RetryConfig | None = None,
        http: HttpClient | None = None,
    ) -> None:
        super().__init__(proxy=proxy, retry=retry, http=http)
        self._auth = auth

    def _build_provider(self) -> ReviewProvider:
        if self._auth is None:
            return AppStoreScraperProvider(**self._provider_kwargs)
        return AppStoreOfficialProvider(
            ConnectAuth(self._credentials(self._auth)), **self._provider_kwargs
        )

    async def _abuild_provider(self) -> ReviewProvider:
        """Async construction: keeps the key-file read off the event loop.

        ``_build_provider`` reads the .p8 from disk, which blocks and has no async
        equivalent to await. Signing is not done here; ``ConnectAuth`` signs
        lazily, per request, so it can refresh an expiring token.
        """
        return await asyncio.to_thread(self._build_provider)

    def _credentials(self, auth: AppStoreAuth) -> ConnectCredentials:
        """Load and validate the .p8, as ``AuthError`` if it cannot be used.

        Everything here fails as a stdlib exception otherwise: a missing file is
        ``FileNotFoundError``, an unparseable key a ``ValueError`` from
        ``cryptography``, and a caller cannot be expected to catch those
        alongside the package's own errors.

        No failure path leaves the PEM reachable from the raised error.
        ``repr=False`` on the field keeps it out of a ``repr``, but an error
        reporter reads frame *locals*, and it walks ``__cause__``. Two things
        follow. The key is unbound before the raise, so this frame does not hold
        it. And the validation failure is re-raised *after* the ``except`` block
        rather than inside it, so no ``__cause__`` or ``__context__`` is attached. That
        matters because the frame that actually fails is
        ``ConnectCredentials.__init__``, generated by ``dataclass``, and it binds
        the key as a parameter where nothing here can reach it. The reason text
        still travels; only the frames are dropped. See
        ``tests/app_reviews/test_credential_hygiene.py``.
        """
        try:
            private_key = Path(auth.key_path).read_text(encoding="utf-8")
        except OSError as exc:
            raise AuthError(
                f"Cannot read the App Store Connect key at {auth.key_path!r}: {exc}"
            ) from exc

        credentials: ConnectCredentials | None = None
        reason: str | None = None
        try:
            credentials = ConnectCredentials(
                key_id=auth.key_id,
                issuer_id=auth.issuer_id,
                private_key=private_key,
            )
        except ValueError as exc:
            reason = str(exc)
        del private_key

        if credentials is None:
            raise AuthError(
                f"The App Store Connect key at {auth.key_path!r} is unusable: {reason}"
            )
        return credentials
